receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318   # OTLP/HTTP

processors:
  memory_limiter:
    check_interval: 2s
    limit_percentage: 75
    spike_limit_percentage: 25
  batch:
    timeout: 1s
    send_batch_size: 512

exporters:
  debug:
    verbosity: detailed

  otlphttp/tempo:
    endpoint: http://tempo:4318

  otlphttp/loki:
    endpoint: http://loki:3100/otlp

extensions:
  health_check: {}

service:
  extensions: [health_check]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlphttp/tempo]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlphttp/loki]
