receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318   # OTLP/HTTP

processors:
  memory_limiter:
    check_interval: 2s
    limit_percentage: 75
    spike_limit_percentage: 25
  batch:
    timeout: 1s
    send_batch_size: 512

exporters:
  # Replacement for the old "logging" exporter
  debug:
    verbosity: detailed

  # Tempo: unchanged, still OTLP/HTTP
  otlphttp/tempo:
    endpoint: http://tempo:4318

  # NEW: send logs to Loki via OTLP HTTP
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    # optional; with plain http it's not strictly needed:
    # tls:
    #   insecure: true

extensions:
  health_check: {}

service:
  extensions: [health_check]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlphttp/tempo]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlphttp/loki]
