server:
  http_listen_port: 3200
  http_listen_address: 0.0.0.0

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317

ingester:
  trace_idle_period: 30s
  max_block_bytes: 1500000
  max_block_duration: 2m  # Reduced for faster S3 flushing in dev
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1

# metrics_generator:
#   registry:
#     external_labels:
#       source: tempo
#       cluster: docker-compose
#   storage:
#     path: /tmp/tempo/generator/wal
#   ring:
#     kvstore:
#       store: memberlist

compactor:
  compaction:
    block_retention: 24h # full retention, no compaction. TODO: change to 24h in production

storage:
  trace:
    backend: s3
    wal:
      path: /tmp/tempo/wal
    s3:
      bucket: tempo-traces
      endpoint: minio:9000
      insecure: true # should be false in production, add tls certificate
      forcepathstyle: true

querier:
  frontend_worker:
    frontend_address: 127.0.0.1:9095

query_frontend:
  max_batch_size: 1048576

memberlist:
  bind_port: 7946
  advertise_port: 7946
  join_members:
    - tempo:7946
