#!/usr/bin/env bash
set -euo pipefail

log() { echo "[$(date -Is)] $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "Missing dependency: $1"; }

INSTALL_ROOT="${INSTALL_ROOT:-/opt/pep}"
REPO_DIR="${REPO_DIR:-$INSTALL_ROOT/prompt_engineering_playground}"

SSM_BASE_PATH="${SSM_BASE_PATH:-/pep/prod/env}"
AWS_REGION="${AWS_REGION:-${REGION:-eu-north-1}}"

# Single deploy version (SHA or tag) used for:
#  - verifying repo state (if it’s a SHA)
#  - IMAGE_TAG for docker-compose pulls
DEPLOY_REF="${DEPLOY_REF:-}"

COMPOSE_FILE="${COMPOSE_FILE:-$REPO_DIR/infra/deploy/docker-compose-prod.yml}"
ENV_FILE="${ENV_FILE:-$REPO_DIR/.env}"

usage() {
  cat <<'EOF'
Usage: ec2_deploy.sh [options]

Single-version deploy:
  DEPLOY_REF is used for BOTH:
   - repo verification (best-effort)
   - IMAGE_TAG for pulling images from ECR via docker compose

Options (or env vars with same name):
  --install-root PATH       (INSTALL_ROOT)  default: /opt/pep
  --repo-dir PATH           (REPO_DIR)      default: $INSTALL_ROOT/prompt_engineering_playground
  --ssm-path PATH           (SSM_BASE_PATH) default: /pep/prod/env
  --region AWS_REGION       (AWS_REGION)    default: eu-north-1
  --compose-file PATH       (COMPOSE_FILE)  default: $REPO_DIR/infra/deploy/docker-compose-prod.yml
  --env-file PATH           (ENV_FILE)      default: $REPO_DIR/.env
  --deploy-ref REF          (DEPLOY_REF)    required: git SHA (recommended) or tag

Example:
  ./infra/deploy/ec2_deploy.sh --deploy-ref <full_sha> --ssm-path /pep/prod/env --region eu-north-1
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install-root) INSTALL_ROOT="$2"; shift 2 ;;
    --repo-dir) REPO_DIR="$2"; shift 2 ;;
    --ssm-path) SSM_BASE_PATH="$2"; shift 2 ;;
    --region) AWS_REGION="$2"; shift 2 ;;
    --compose-file) COMPOSE_FILE="$2"; shift 2 ;;
    --env-file) ENV_FILE="$2"; shift 2 ;;
    --deploy-ref) DEPLOY_REF="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1 (use --help)" ;;
  esac
done

need git
need aws
need docker

if ! docker compose version >/dev/null 2>&1; then
  die "Docker Compose plugin not found. Install Docker Compose v2 (docker compose ...)."
fi

[[ -n "$DEPLOY_REF" ]] || die "DEPLOY_REF is required (use --deploy-ref ...)"

log "1) Verifying repo state"
[[ -d "$REPO_DIR/.git" ]] || die "Repo not found at $REPO_DIR - workflow should have cloned it"

ACTUAL_SHA="$(git -C "$REPO_DIR" rev-parse HEAD)"
log "   Repo dir:    $REPO_DIR"
log "   Current SHA: $ACTUAL_SHA"
log "   Deploy ref:  $DEPLOY_REF"

# If DEPLOY_REF looks like a SHA, verify it matches the checked out commit (prefix match allowed)
if [[ "$DEPLOY_REF" =~ ^[0-9a-fA-F]{7,40}$ ]]; then
  if [[ "$ACTUAL_SHA" != "$DEPLOY_REF"* && "$DEPLOY_REF" != "$ACTUAL_SHA"* ]]; then
    die "Deploy ref mismatch! Expected (sha): $DEPLOY_REF, Actual: $ACTUAL_SHA"
  fi
  log "   Deploy ref verified (sha match)"
else
  log "   Deploy ref is not a SHA (tag/other). Skipping strict SHA match verification."
fi

# Single version => IMAGE_TAG = DEPLOY_REF
export IMAGE_TAG="$DEPLOY_REF"
log "   IMAGE_TAG set to: $IMAGE_TAG"

[[ -f "$COMPOSE_FILE" ]] || die "Compose file not found: $COMPOSE_FILE"

log "2) Fetching SSM params -> .env"
mkdir -p "$INSTALL_ROOT"
log "   SSM path: $SSM_BASE_PATH"
log "   Region:   $AWS_REGION"

TMP_JSON="$(mktemp)"
trap 'rm -f "$TMP_JSON"' EXIT

aws ssm get-parameters-by-path \
  --region "$AWS_REGION" \
  --with-decryption \
  --recursive \
  --path "$SSM_BASE_PATH" \
  --output json >"$TMP_JSON"

mkdir -p "$(dirname "$ENV_FILE")"

if command -v python3 >/dev/null 2>&1; then
  SSM_BASE_PATH="$SSM_BASE_PATH" ENV_FILE="$ENV_FILE" python3 - "$TMP_JSON" <<'PY'
import json, os, sys

json_path = sys.argv[1]
with open(json_path, "r", encoding="utf-8") as f:
    payload = json.load(f)

prefix = os.environ["SSM_BASE_PATH"].rstrip("/") + "/"
env_path = os.environ["ENV_FILE"]

params = payload.get("Parameters", [])
items = []
for p in params:
    name = p.get("Name", "")
    value = p.get("Value", "")
    if not name.startswith(prefix):
        continue
    key = name[len(prefix):]
    value = value.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\\n")
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    items.append((key, value))

items.sort(key=lambda kv: kv[0])

with open(env_path, "w", encoding="utf-8") as out:
    out.write("# Generated by infra/deploy/ec2_deploy.sh\n")
    out.write(f"# Source: SSM {prefix[:-1]}\n\n")
    for k, v in items:
        out.write(f'{k}="{v}"\n')
PY
elif command -v jq >/dev/null 2>&1; then
  prefix="${SSM_BASE_PATH%/}/"
  {
    echo "# Generated by infra/deploy/ec2_deploy.sh"
    echo "# Source: SSM ${prefix%/}"
    echo
    jq -r --arg p "$prefix" '
      .Parameters
      | map(select(.Name | startswith($p)))
      | sort_by(.Name)
      | .[]
      | (.Name | sub("^" + $p; "")) + "=" + ( .Value | gsub("\r\n|\r|\n"; "\\n") | @json )
    ' "$TMP_JSON" | sed -E 's/=(.+)$/=\1/'
  } >"$ENV_FILE"
else
  die "Need python3 (preferred) or jq to convert SSM JSON into a .env file"
fi

chmod 600 "$ENV_FILE" || true
log "   Wrote: $ENV_FILE"

log "3) Logging into ECR registries referenced by compose (after env expansion)"
TMP_COMPOSE_CFG="$(mktemp)"
trap 'rm -f "$TMP_JSON" "$TMP_COMPOSE_CFG"' EXIT

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" config >"$TMP_COMPOSE_CFG"

mapfile -t ECR_REGISTRIES < <(
  grep -oE '[0-9]{12}\.dkr\.ecr\.[a-z0-9-]+\.amazonaws\.com' "$TMP_COMPOSE_CFG" \
    | sort -u
)

if [[ ${#ECR_REGISTRIES[@]} -eq 0 ]]; then
  log "   No private ECR registries found in expanded compose config (skipping ECR login)."
else
  for reg in "${ECR_REGISTRIES[@]}"; do
    region="$(echo "$reg" | cut -d. -f4)"
    log "   -> docker login $reg (region: $region)"
    aws ecr get-login-password --region "$region" | docker login --username AWS --password-stdin "$reg" >/dev/null
  done
fi

log "4) Whitelist reset: remove ALL containers + images (KEEP volumes)"
if [[ -n "$(docker ps -aq)" ]]; then
  docker rm -f $(docker ps -aq) || true
fi
if [[ -n "$(docker images -aq)" ]]; then
  docker rmi -f $(docker images -aq) || true
fi
docker network prune -f || true
docker builder prune -f || true
# DO NOT prune volumes

log "5) docker compose pull (exact IMAGE_TAG=$IMAGE_TAG)"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" pull

log "6) docker compose up"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --no-build --force-recreate --remove-orphans

log "7) Done"
